# Generated by Anaconda 34.25.0.29
# Generated by pykickstart v3.32
#version=RHEL9
# Use graphical install
graphical

%addon com_redhat_kdump --disable

%end

%addon com_redhat_oscap
    content-type = scap-security-guide
    datastream-id = scap_org.open-scap_datastream_from_xccdf_ssg-rhel9-xccdf-1.2.xml
    xccdf-id = scap_org.open-scap_cref_ssg-rhel9-xccdf-1.2.xml
    profile = xccdf_org.ssgproject.content_profile_stig_gui
%end

# Keyboard layouts
keyboard --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=eth0 --ipv6=auto --activate
network  --hostname=rhel8work

%packages
@^workstation-product-environment
aide
audit
fapolicyd
firewalld
opensc
openscap
openscap-scanner
openssh-server
openssl-pkcs11
policycoreutils
rng-tools
rsyslog
rsyslog-gnutls
scap-security-guide
tmux
usbguard
# for tpm unlocking
clevis-dracut 
clevis-luks
clevis-systemd
# don't install
-iprutils
-krb5-workstation
-rsh-server
-sendmail
-telnet-server
-tftp-server
-tuned
-vsftpd

%end

# Run the Setup Agent on first boot
firstboot --disable

# Generated using Blivet version 3.4.0
ignoredisk --only-use=sda
# Partition clearing information
clearpart --none --initlabel
# Disk partitioning information
part /boot --fstype="xfs" --ondisk=sda --size=1024
part /boot/efi --fstype="efi" --ondisk=sda --size=600 --fsoptions="umask=0077,shortname=winnt"
part pv.308 --fstype="lvmpv" --ondisk=sda --grow --encrypted --passphrase='temppass' --luks-version=luks2
volgroup rhel_test --pesize=4096 pv.308
logvol /home --fstype="xfs" --percent=8 --name=home --vgname=rhel_test
logvol /var --fstype="xfs" --percent=8 --name=var --vgname=rhel_test
logvol /tmp --fstype="xfs" --percent=8 --name=tmp --vgname=rhel_test
logvol swap --fstype="swap" --size=4036 --name=swap --vgname=rhel_test
logvol /var/log --fstype="xfs" --percent=10 --name=var_log --vgname=rhel_test
logvol /var/log/audit --fstype="xfs" --percent=8 --name=var_log_audit --vgname=rhel_test
logvol /var/tmp --fstype="xfs" --percent=8 --name=var_tmp --vgname=rhel_test
logvol / --fstype="xfs" --percent=40 --name=root --vgname=rhel_test

# System timezone
timezone America/Detroit --utc

# Root password
rootpw --iscrypted $6$Tv2ko9/nD/RGG5TI$kM.5TiKQj4pCGsu5DYlAOVSvI8RgJKL00GFmxcnelS.wlXxj/nc/Y4iSKK1RTG7zf13HnMr8v7I6HBu7thVHY.
#rootpw --lock
user --groups=wheel --name=install_user --password=$6$Tv2ko9/nD/RGG5TI$kM.5TiKQj4pCGsu5DYlAOVSvI8RgJKL00GFmxcnelS.wlXxj/nc/Y4iSKK1RTG7zf13HnMr8v7I6HBu7thVHY. --iscrypted --gecos="install_user"

reboot

%post
# add install_user public key
mkdir /home/install_user/.ssh
chmod 700 /home/install_user/.ssh
touch /home/install_user/.ssh/authorized_keys
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLtdnWVvIvdQ22wTg0pjwDSW/AxqWxVkC6yGINIipY29cdEj7yackIHHlu2Wdlok8haXXgnY/ZfAE2peS9dHNOsIZvspp8lYupedu+GA2ebsn+LR+6Sj1tDyHITPvsZz+Yq722r+s3DgsniG3LYgtkO87lBDpl/XsWZSThFbJ//Ps8pConX3yTC6OA0tNjF8FaEgdWKUsWKBTF1HXcw5xF8HA1OpPcUs92uxiLXZRpcTci+2soYi8gKehO6bjMgnY1IGMMIzwhPzKv8HExe4UpcmD6DhoZsFsHwsJZKxSdGDBVqcOXgZleHobIsUjlbtU3rTy/P2+HV75+jQOrLJix' > /home/install_user/.ssh/authorized_keys
chmod 400 /home/install_user/.ssh/authorized_keys
chown -R install_user: /home/install_user/

# use tpm2 to unlock disk automatically
clevis luks bind -k - -d /dev/sda3 tpm2 '{"hash":"sha1","key":"rsa"}' <<< 'temppass'
dracut -fv --regenerate-all
%end